### ISSUE TITLE
Cannot find module cws_linux_72

### ISSUE THREAD

**Issue by manpreetsingh2011** [soyuka/signalhubws#17]
Running the following command gives an error.
`signalhubws listen -p 8080`

```
internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module '/usr/lib/node_modules/signalhubws/node_modules/@clusterws/cws/dist/cws_linux_72'
Require stack:
- /usr/lib/node_modules/signalhubws/node_modules/@clusterws/cws/dist/index.js
- /usr/lib/node_modules/signalhubws/server.js
- /usr/lib/node_modules/signalhubws/bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/usr/lib/node_modules/signalhubws/node_modules/@clusterws/cws/dist/index.js:30:16)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/node_modules/signalhubws/node_modules/@clusterws/cws/dist/index.js',
    '/usr/lib/node_modules/signalhubws/server.js',
    '/usr/lib/node_modules/signalhubws/bin.js'
  ]
}
```
I am on Ubuntu 18.04, running node version `v12.10.0`

Solution:
The file is present in the [GIT Repo for clusterws/cws](https://github.com/ClusterWS/cWS/tree/master/dist)
Updating the version of `@clusterws/cws` in `package.json` from `0.11.0` to `0.15.2` solves the problem for me.

**Comment by manpreetsingh2011** [comment]
Pull request: #18

**Comment by soyuka** [comment]
thanks @manpreetsingh2011 !
